CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y

# NET
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_NET_HOSTNAME="doit_esp32_devkit_v1"
CONFIG_NET_MGMT_EVENT_STACK_SIZE=1500

# ENC28J60
CONFIG_ETH_ENC28J60_RX_THREAD_STACK_SIZE=1500

# SYSTEM
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1500

# ETH
CONFIG_NET_IF_MAX_IPV4_COUNT=1